import type { Metadata } from 'next'
import '@mantine/core/styles.css'
import { Container } from '@mantine/core'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Container strategy="block" size={500} my={40}>
        {children}
      </Container>
    </>
  )
}
