packages:
  - "api"
  - "web"
syncInjectedDepsAfterScripts:
  - build
injectWorkspacePackages: true

catalog:
  typescript: ^5.9.3
  prettier: "^3.6.2"
  eslint: "^9.38.0"
  zod: "^4.1.12"
  nanoid: "^3.3.11"
