services:
  kanban-db:
    container_name: kanban-db-dev
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - kanban-db-data-dev:/var/lib/postgresql/data

volumes:
  kanban-db-data-dev:
