services:
  kanban-web:
    container_name: kanban-web-prod
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      SSR_API_URL: ${SSR_API_URL}
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    networks:
      - kanban-network

  kanban-api:
    container_name: kanban-api-prod
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      COOKIE_SECURE: ${COOKIE_SECURE}
      CORS_ORIGIN: ${CORS_ORIGIN}
      WEB_DOMAIN: ${WEB_DOMAIN}
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
      target: production
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - kanban-network

  kanban-db:
    container_name: kanban-db-prod
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kanban
    ports:
      - "5432:5432"
    volumes:
      - kanban-db-data:/var/lib/postgresql/data
    networks:
      - kanban-network

volumes:
  kanban-db-data:

networks:
  kanban-network:
    driver: bridge
