# ------------------------------------------------------
# Stage 1 — Base setup
# ------------------------------------------------------
ARG NODE_VERSION=26.9.0
ARG PNPM_VERSION=12.4.2

FROM node:${NODE_VERSION}-alpine AS base
ENV CI=true
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g --allow-scripts=pnpm pnpm@${PNPM_VERSION}
RUN pnpm config set store-dir /pnpm/store
WORKDIR /app

# ------------------------------------------------------
# Stage 2 — Dependencies
# ------------------------------------------------------
FROM base AS deps
WORKDIR /app
COPY package.json ./
COPY pnpm-workspace.yaml ./
COPY pnpm-lock.yaml ./
COPY api/package.json ./api/package.json
RUN pnpm --filter=api install --frozen-lockfile

# ------------------------------------------------------
# Stage 3 — Build
# ------------------------------------------------------
FROM deps AS build
WORKDIR /app
COPY . .
RUN pnpm --filter=api build
RUN pnpm deploy --filter=api --prod /opt/api-deploy

# ------------------------------------------------------
# Stage 4 — Production
# ------------------------------------------------------
FROM base AS production
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY --from=build /app/api/dist ./dist
COPY --from=build /opt/api-deploy ./
COPY api/package.json ./
EXPOSE 3000
# CMD tail -f /dev/null
CMD ["node", "dist/main.js"]