name: Publish Docker Images

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/Dockerfile.api
            appname: maciejgarncarski/kanban-api
            image: ghcr.io/maciejgarncarski/kanban-api
          - dockerfile: ./docker/Dockerfile.web
            appname: maciejgarncarski/kanban-web
            image: ghcr.io/maciejgarncarski/kanban-web
            build_args: |
              NEXT_PUBLIC_API_URL=https://kanban-api.maciej-garncarski.pl
              NODE_ENV=production

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          target: "prod"
          file: ${{ matrix.dockerfile }}
          push: true
          build-args: ${{ matrix.build_args }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
